### ISSUE TITLE
pod install error - ERROR: Parsing unable to continue due to parsing error:

### ISSUE THREAD

**Issue by Aathi** [shrikanthkr/ReactNativeAudioStream#1]
@shrikanthkr  Any idea about this error?
<img width="695" alt="ios_ _bash_ _202x49" src="https://cloud.githubusercontent.com/assets/5355180/14504351/bb82cb8a-01b4-11e6-99a7-5a69da24b239.png">

**Comment by Aathi** [comment]
Fixed...

```
$ gem install cocoapods --pre
Fetching: xcodeproj-0.24.0.gem (100%)
Successfully installed xcodeproj-0.24.0
Fetching: cocoapods-core-0.37.0.beta.1.gem (100%)
Successfully installed cocoapods-core-0.37.0.beta.1
Fetching: cocoapods-0.37.0.beta.1.gem (100%)
Successfully installed cocoapods-0.37.0.beta.1
Parsing documentation for xcodeproj-0.24.0
Installing ri documentation for xcodeproj-0.24.0
Parsing documentation for cocoapods-core-0.37.0.beta.1
Installing ri documentation for cocoapods-core-0.37.0.beta.1
Parsing documentation for cocoapods-0.37.0.beta.1
Installing ri documentation for cocoapods-0.37.0.beta.1
Done installing documentation for xcodeproj, cocoapods-core, cocoapods after 7 seconds
3 gems installed

$ pod install
Update all pods
[!] ERROR: Parsing unable to continue due to parsing error:

$ gem uninstall psych
Successfully uninstalled psych-2.0.13

$ pod install
```

**Comment by shrikanthkr** [comment]
@Aathi Hi, sorry was not available at that time. Anyways its fixed right.. :+1:

**Comment by Aathi** [comment]
@shrikanthkr No problem .tnx

**Comment by shrikanthkr** [comment]
@Aathi did that work ? U r able to hear the songs?

**Comment by Aathi** [comment]
@shrikanthkr Ya I have fixed and I have interacted into my app  it works like charm. 💃  But we have a problem here if we press the play button twice it starts to play again and again. If  we want to stop this  we need to bring other tasks too such as 

```
1. stop
2. duration
3. resume
4. mute
5. unmute
6. pause
```

please check this
http://cocoadocs.org/docsets/StreamingKit/0.0.13/Classes/STKAudioPlayer.html#//api/name/play:

**Comment by shrikanthkr** [comment]
@Aathi yeah this is just a working sample....
